name: cat_tourism_hub
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  gap:
  cached_network_image: ^3.4.0
  provider:
  http:
  intl:
  flutter_svg:
  image_picker:
  image_picker_for_web:
  file_picker:
  url_strategy:
  firebase_core:
  firebase_core_web:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  firebase_ui_auth:
  firebase_crashlytics:
  sidebarx:
  dotted_border:
  go_router:
  simple_chips_input:
  shared_preferences:
  loading_animation_widget:
  flutter_typeahead:
  flutter_iconpicker: ^3.4.5
  image_collage: ^0.0.4
  auto_size_text: ^3.0.0
  fan_carousel_image_slider: ^1.0.1
  skeletonizer: ^1.4.2
  cupertino_icons: ^1.0.6
  firebase_app_check: ^0.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name:

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
